[tool.black]
line-length = 88

[tool.ruff]
line-length = 88
target-version = "py38"
exclude = [
    "setup.py"
]

[tool.ruff.isort]
known-first-party = ["ssh_crypt"]

[tool.ruff.flake8-quotes]
inline-quotes = "double"
