# skips tests on windows
# todo: adds mypy checks

name: Master build

on:
  push:
    branches:
      - master
  pull_request:


jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11",]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python interpreter [${{ matrix.python-version }}]
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies from tests/requirements.txt
        shell: bash
        run: |
            python -m pip install --upgrade pip
            pip install setuptools build wheel twine
            pip install -r requirements.txt
            pip install pytest ruff

      - name: Static checks (ruff)
        shell: bash
        run: |
           ruff check --fix .

      - name: Runtime checks (pytest)
        if: ${{ matrix.os != 'windows-latest' }}
        shell: bash
        env:
          PYTHONPATH: .
        run: |
          py.test -vvs tests

